version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: music_app_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: music_app_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/user.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - music_app_net

  mongo:
    image: mongo:6
    container_name: music_app_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - music_app_net

  redis:
    image: redis:latest
    container_name: music_app_redis
    ports:
      - "6379:6379"
    networks:
      - music_app_net

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: music_app_server
    ports:
      - "8086:8086"
    depends_on:
      - postgres
      - mongo
      - redis
    environment:
      - POSTGRES_DSN=postgres://postgres:admin@postgres:5433/music_app_db?sslmode=disable
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_ADDR=redis:6379
    volumes:
      - .:/app
    networks:
      - music_app_net

volumes:
  postgres_data:
  mongo_data:

networks:
  music_app_net:
    driver: bridge
